stages:
  - build
  - test
  - deploy

build-job:
  image: node:latest
  stage: build
  only:
  - master
  before_script: 
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git remote remove gitlab || true
    - git remote add gitlab "http://ELREST_MAINTAINER:${ELREST_MAINTAINER}@${CI_REPOSITORY_URL#*@}"
  script:
    - npm install
    - npm run build
    - git add --all
    - git commit -m "CI Build" || true

    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#http*:}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } >> .npmrc

    - echo "Created the following .npmrc:"; cat .npmrc

    
    - npm version patch
    - git push gitlab HEAD:$CI_COMMIT_REF_NAME -o ci.skip
    - git push gitlab --tags -f -o ci.skip
    - npm publish --patch
