stages:
  - build
  - test
  - deploy

build-job:
  image: node:latest
  stage: build
  script:
    - npm install
    - npm run build
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#http*:}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } >> .npmrc

    - echo "Created the following .npmrc:"; cat .npmrc
    - npm publish --patch