stages:
  - build
  - test
  - deploy

build-job:
  image: node:latest
  stage: build
  variables:
  #  GIT_SUBMODULE_STRATEGY: recursive
  #  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 4
    GIT_STRATEGY : clone
  only:
  - master
  - develop
  before_script: 
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git remote remove gitlab || true
    - git remote add gitlab "http://ELREST_MAINTAINER:${ELREST_MAINTAINER}@${CI_REPOSITORY_URL#*@}"
  script:
    - |
      {
        echo "email=slavomir.sidor@elrest.zz"
        echo "registry=${WAG_NPM_RPOSITORY}/"
        echo "${WAG_NPM_RPOSITORY#http*:}/:_authToken=\${WAGO_NPM_REPOSITORY_TOKEN}"
        echo "${WAGO_NPM_X86_64_REPOSITORY#http*:}/:_authToken=\${WAGO_NPM_REPOSITORY_TOKEN}"
      } > .npmrc
    - cat .npmrc
    - npm install --save
    - npm run build
    - git add --all
    - git commit -m "CI Build" || true
    - npm version minor
    - git push gitlab HEAD:$CI_COMMIT_REF_NAME -o ci.skip
    - git push gitlab --tags -f -o ci.skip
    - npm publish --minor --registry ${WAGO_NPM_X86_64_REPOSITORY}/

